// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-05-25 21:36:48.6332268 +0100 WAT m=+0.102936401

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Essami nader",
            "email": "nader@craftfoundry.tech"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Cinvoice": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Customer Invoice",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/acc": {
            "get": {
                "description": "Send To Backend user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Confirm Account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/bwl": {
            "get": {
                "description": "welcome pack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Welcome Backend user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/cokride": {
            "get": {
                "description": "Send To Company When Ride is Confirmed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Ride confirmation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/colate": {
            "get": {
                "description": "Send To Company when Driver is late",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Driver Late",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/cono": {
            "get": {
                "description": "Send To Company When there is no driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "No Driver",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/conodelivery": {
            "get": {
                "description": "Send To Company When Cancelled their Delivery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Cancelled delivery",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/conoride": {
            "get": {
                "description": "Send To Company When their ride is Cancelled",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Ride cancellation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/coyesdelivery": {
            "get": {
                "description": "Send to Company When Their Delivery is Confirmed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Delivery Confirmation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/cwl": {
            "get": {
                "description": "welcome pack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Welcome Company",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/dnc": {
            "get": {
                "description": "Send For Backend User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "No Access",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/dwl": {
            "get": {
                "description": "welcome pack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Welcome driver",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/fex": {
            "get": {
                "description": "Manage Document",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Expired Document",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/fre": {
            "get": {
                "description": "Manage Document",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Refused Files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/fva": {
            "get": {
                "description": "Manage Document",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Validated File",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/invoice": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Driver Invoice Template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/late": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "driver alert late  template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/latecustomer": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Customer Late",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/no": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "No driver template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/noclient": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "client cancel ride template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/nocustomer": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "No customer",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/nod": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Driver Cancel Client Ride",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/nodelivery": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Cancel delivery template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/nodeliveryc": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Delivey Cancelled",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/noride": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Ride canceled Template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/noridec": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Driver  Cancel Ride",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/noy": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "not way driver template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/okride": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Confirmed Ride template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/okridec": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Driver Confirm Ride",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/prwl": {
            "get": {
                "description": "Welcome pack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Welcome parrinage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/pswl": {
            "get": {
                "description": "welcome pack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Welcome passenger",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/us": {
            "get": {
                "description": "Send To Backend user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Permission for acces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/yesdelic": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "text/html"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Driver Confirm Delivery",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/yesdelivery": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Confirmed Delivery Template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        },
        "/yesrd": {
            "get": {
                "description": "generating template  which will be sended to driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Ride confirmed by client template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Models.Driver"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Models.Driver": {
            "type": "object",
            "properties": {
                "address_pickup_complement": {
                    "type": "string"
                },
                "arrival_addr": {
                    "type": "string"
                },
                "cancel_text": {
                    "type": "string"
                },
                "canceladditional_text": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "date_time": {
                    "type": "string"
                },
                "deliveryride_id": {
                    "type": "string"
                },
                "departure_addr": {
                    "type": "string"
                },
                "driver_full_name": {
                    "type": "string"
                },
                "driver_sirenid": {
                    "type": "string"
                },
                "driverphone_number": {
                    "type": "string"
                },
                "estimate_duration": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "modification_text": {
                    "type": "string"
                },
                "passanger_name": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "request_modification": {
                    "type": "string"
                },
                "requestes_timate_pickup_date": {
                    "type": "string"
                },
                "reservation_price": {
                    "type": "string"
                },
                "total_price": {
                    "type": "string"
                },
                "vehicle_type": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "backendtmpl.herokuapp.com",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Templates Manager API",
	Description: "This is a sample service for generating templates",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
